### PR TITLE
Quest 1 explainers

### PR DESCRIPTION
**Pull request by ElliotFriend**
Added comments to the rust files in the `src/` directory. Also, added a README to the directory, although I'm not sure if that's the direction we want to go. Would love your thoughts, @tyvdh!

<a href="https://gitpod.io/#https://github.com/tyvdh/soroban-pioneer-quest/pull/6"></a>

### CODE REVIEW

**Comment by kalepail** [comment]
This looks great! But let’s put it in the private repo so we don’t leak the first quest completely 🙂

**Comment by kalepail** [comment]
Let’s also separate the story from the instructions into two separate files

**Comment by kalepail** [comment]
Also if it’s possible id love to come up with a clear tldr top line task ask for pros to be able to read without needing to read the whole thing

**Comment by ElliotFriend** [comment]
> This looks great! But let’s put it in the private repo so we don’t leak the first quest completely slightly_smiling_face

Feel like a dummy for that lol. I reset and force-pushed to this branch, which "should" at least make it harder for anyone to find that README info here. I'll add that to the private repo momentarily.

For this repo, I think I'll keep the comments in lib/test.rs, and probably give a very brief "here's what you can expect from this file" inside a README/STORY.md file.

**Comment by ElliotFriend** [comment]
I've now realized that the story chunks for quest 0 and quest 1 are different. And the actual tasks to complete are (similar but still) different. Leads me to a couple questions:

- How/when should the removed content make it back into this repo's README?
- I suppose I can put all of the storyline into the `STORY.md` file for quest 0?

**Comment by kalepail** [comment]
Maybe we rename the quest to 0 vs 1 here and keep instructions more around general expectations for quests vs actually completing the quest. Does that make sense? So like the flow vs any specifics or step by steps

**Comment by kalepail** [comment]
Also it’s fine to leak the 0 story here now. Sorry about the confusion

**Comment by kalepail** [comment]
- Including the first part of the story as a Prologue
- Renamed some things to Pioneer quest and 0 quest

**Comment by ElliotFriend** [comment]
Love it! Thanks for clearing those questions up!

**Pull request merged**
