### PR TITLE
Making a few changes and additions to README

### PR DESCRIPTION
**Pull request by ElliotFriend**
- [ ] ~~Add a table with the quest schedule~~
- [x] Explain the terminal windows (sandbox vs. futurenet, etc.)
- [x] Explain the open ports

### CODE REVIEW

**Comment by ElliotFriend** [comment]
Screenshot from 2022-11-10 14-25-59

Screenshot from 2022-11-10 15-02-02

**Comment by kalepail** [comment]
Let's actually put the Questing schedule on the [main quest README](https://github.com/tyvdh/soroban-quest/blob/main/README.md)

**Comment by ElliotFriend** [comment]
Just that one, or both places? And, is UTC ok to use for timezone?

**Comment by kalepail** [comment]
Just the one. Let's leave the Pioneer repo as Series agnostic as possible

**Comment by ElliotFriend** [comment]
Sounds good!

**Pull request merged**
