### PR TITLE
Adding a Video section, to hold the embed

### PR DESCRIPTION
**Pull request by ElliotFriend**
I don't know of an easy way to directly embed from youtube, but I think I can drag-n-drop it from the GitHub site.

### CODE REVIEW

**Comment by ElliotFriend** [comment]
Hmmm... GitHub wants the video to be less than 10MB. Maybe I can render it at 720p or something...

**Comment by kalepail** [comment]
Just link to your channel. That's fine. No need to embed really

**Comment by ElliotFriend** [comment]
@tyvdh How does this look? Should I use the video thumbnail instead of just a text link?

**Comment by kalepail** [comment]
If you can link to a video thumbnail I'd do that for sure

**Comment by ElliotFriend** [comment]
Trying to add this here so I can use the github link


soroban-pioneer-quest-thumbnail

**Pull request merged**
